name: MATLAB demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: >
            Statistics_and_Machine_Learning_Toolbox
            Curve_Fitting_Toolbox
      - name: Run demo script
        uses: matlab-actions/run-command@v2
        with:
          command: cd demo; sila_demo
